# Generated by Django 6.0.6 on 2026-06-11 04:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=3)),
                ('mutated_priority', models.IntegerField(choices=[(1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=3)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='pending', max_length=120)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('interval', models.CharField(blank=True, choices=[('every_1_minute', 'Every 1 min'), ('every_5_minutes', 'Every 5 mins'), ('every_1_hour', 'Every 1 hour')], max_length=50, null=True)),
                ('is_cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeadLetterQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_child', to='core.job')),
                ('parent_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_parent', to='core.job')),
            ],
            options={
                'unique_together': {('parent_job', 'child_job')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_jobs', through='core.JobDependency', to='core.job'),
        ),
    ]
